---
- name: install pre package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - policycoreutils
    - openssh-server
    - openssh-clients
    - postfix
    - firewalld
