---
- name: start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: 
    - sshd
    - postfix
    - firewalld
    
- name: "configured firewalld (open port:{{ port }})"
  firewalld:
    port: "{{ port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
    