---
- name: set mongodb repository  # [warn]blockinfileで書き直す
  shell: |
    echo "[mongodb]" >> /etc/yum.repos.d/mongodb.repo
    echo "name=MongoDB Repository" >> /etc/yum.repos.d/mongodb.repo
    echo "baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/" >> /etc/yum.repos.d/mongodb.repo
    echo "gpgcheck=0" >> /etc/yum.repos.d/mongodb.repo
    echo "enabled=1" >> /etc/yum.repos.d/mongodb.repo
  when: installed_mongodb.stat.exists == False
  
- name: install mongodb
  yum:
    name: mongodb-org
    state: present
    
- name: start mongodb
  service: 
    name: mongod
    state: started
    enabled: yes
