---
- name: install base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - libselinux-python
    - firewalld

- name: install rails dependent packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc-c++
    - glibc-headers
    - openssl-devel
    - readline
    - libyaml-devel
    - readline-devel
    - zlib
    - zlib-devel
    - bzip2
    - sqlite-devel
