---
- name: clone rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /usr/local/rbenv
    
- name: add export path
  blockinfile:
    dest: ~/.bashrc
    block: |
      export RBENV_ROOT="/usr/local/rbenv"
      export PATH="${RBENV_ROOT}/bin:${PATH}"
      eval "$(rbenv init -)"
    marker: "#{mark} rbenv PATH"
    