---
- name: clone ruby
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /usr/local/rbenv/plugins/ruby-build

- name: install ruby
  shell: "rbenv install -v {{ ruby_version }}"
  
- name: rbenv rehash
  shell: rbenv rehash
  
- name: "rbenv global {{ ruby_version }}"
  shell: "rbenv global {{ ruby_version }}"