---
- name: gem update
  shell: gem update --system
  
- name: install rails
  shell: "gem install --no-ri --no-rdoc rails  --version {{ rails_version }}"
  
- name: install bundler
  shell: gem install bundler
  
- name: rbenv rehash
  shell: rbenv rehash
  